"""Self-contained HTML review report. Deterministic — no LLM involved."""

import html
from pathlib import Path

SEV_ORDER = {"critical": 0, "major": 1, "minor": 2}
SEV_COLOR = {"critical": "#c62828", "major": "#e65100", "minor": "#8d6e63"}

STYLE = """
:root { color-scheme: light dark; --fg: #1c1c1c; --bg: #fbfaf8; --card: #fff;
  --muted: #666; --line: #e3ded6; }
@media (prefers-color-scheme: dark) { :root { --fg: #e8e6e3; --bg: #16181d;
  --card: #1f232b; --muted: #9aa0a6; --line: #333944; } }
* { box-sizing: border-box; }
body { font: 15px/1.55 -apple-system, "Segoe UI", sans-serif; margin: 0;
  color: var(--fg); background: var(--bg); }
main { max-width: 860px; margin: 0 auto; padding: 40px 24px 80px; }
h1 { font-size: 26px; margin: 0 0 4px; }
.sub { color: var(--muted); margin-bottom: 28px; }
.verdict { display: inline-block; padding: 6px 14px; border-radius: 6px;
  font-weight: 600; margin: 12px 0 24px; color: #fff; }
.card { background: var(--card); border: 1px solid var(--line);
  border-radius: 10px; padding: 18px 20px; margin-bottom: 16px; }
.sev { display: inline-block; font-size: 12px; font-weight: 700;
  letter-spacing: .04em; color: #fff; border-radius: 4px; padding: 2px 8px;
  margin-right: 8px; vertical-align: 2px; }
.loc { font-family: ui-monospace, monospace; font-size: 13px;
  color: var(--muted); margin: 6px 0 10px; }
.ev { border-left: 3px solid var(--line); padding: 6px 12px; margin-top: 12px;
  color: var(--muted); font-size: 13.5px; }
.ev b { color: var(--fg); }
footer { color: var(--muted); font-size: 13px; margin-top: 40px; }
"""


def write_html_report(path, meta, result):
    findings = sorted(result["findings"],
                      key=lambda f: SEV_ORDER.get(f.get("severity"), 3))
    crit = sum(1 for f in findings if f.get("severity") == "critical")
    if findings:
        verdict_txt = (f"Request changes — {len(findings)} confirmed"
                       f" finding(s), {crit} critical")
        verdict_bg = "#c62828" if crit else "#e65100"
    else:
        verdict_txt = "Approve — no confirmed defects"
        verdict_bg = "#2e7d32"

    cards = []
    for i, f in enumerate(findings, 1):
        sev = f.get("severity", "?")
        ver = f.get("verification") or {}
        ev = ""
        if ver:
            ev = (f'<div class="ev"><b>Verified'
                  f' ({html.escape(ver.get("confidence", "?"))} confidence)'
                  f':</b> {html.escape(str(ver.get("evidence", ""))[:600])}'
                  f'</div>')
        cards.append(f"""
<div class="card">
  <span class="sev" style="background:{SEV_COLOR.get(sev, '#607d8b')}">{html.escape(sev.upper())}</span>
  <strong>{i}. {html.escape(f.get('title', 'finding'))}</strong>
  <div class="loc">{html.escape(str(f.get('file')))}:{f.get('line')} &middot; {html.escape(str(f.get('category')))}</div>
  <div>{html.escape(f.get('description', ''))}</div>
  {ev}
</div>""")

    stages = result.get("stages", [])
    stage_txt = " &rarr; ".join(
        f"{s['stage']}" + (f" ({s.get('findings', s.get('confirmed', '?'))})"
                           if 'error' not in s else " (failed)")
        for s in stages) or "single pass"

    doc = f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RevGuard review: {html.escape(meta['title'])}</title>
<style>{STYLE}</style></head><body><main>
<h1>Code review: {html.escape(meta['title'])}</h1>
<div class="sub">{html.escape(meta.get('pr_description', ''))}</div>
<span class="verdict" style="background:{verdict_bg}">{verdict_txt}</span>
{''.join(cards) if cards else '<div class="card">Every reviewer hypothesis was rejected under adversarial verification.</div>'}
<footer>Pipeline: {stage_txt} &middot; {result.get('seconds', '?')}s &middot;
${result.get('cost_usd', 0):.2f} &middot; generated by RevGuard — every
finding above survived an adversarial verification agent instructed to
disprove it.</footer>
</main></body></html>"""
    Path(path).write_text(doc)
